server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/authenticationdb
    username: root
    password: 2439
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  private-key: MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQC7BeP/uV73kb2/0xCatGQdHU9o8bpDS3GRNVkWU9h4T7oHJ6rQwbTHIe0+V/K3+xjIVGzP15DF/rTb/erZnFSea4TbFktgYh8dOa0J9xeQpSOqjxPUnoGaWeBfLe5Q/cIZ1THDXtMROhRZepS11kEm9xUEK5IBZ24biMGX8WnaBL7pIgaF2esCuCVKTIP+E0Lu0eHKZScKbyiAfbVc4IQj55VKKzA+QvbgoM+wl9C7URt+hF9K3NjOyp+2xAdzqehl+MlxmoqVmnSZUJnsfath8zzsboXY1nC5E+101Su4j7mJmY2SQMllobUTNbl2dtuQkURBJxZcnb71Bcx+fnIzAgMBAAECggEAPIaMApMh1louv/lVKtQNgFSfgfWVE7lDQDy1H6Iz8L/Qkwc140iFMlra9i2tSfhzzUVxT5RScJldO8MBsbpDsl9WiDa/XypyKlmjlBGI6VFgaQ7T2qAPjn3evL7XHRP6sLSL3c/+29jhhBHFNdHolO0quoZFQroP6s5H5N4GpT0NLM2duPtTmByKkxZg3ktSGAU+uiGErAmMGxUcHJ8Nlwv2G40redzGbO5yT5dJRuE31n7kAXjYEFEedqiRTOUfdU5V+J7FgFFUSryEuOsP13pJTmMc1cq5fx5SaDrUqiCiWIMSN7FhnT9EUqfG0/pFGo8+m89jOkrx+gboQsvyhQKBgQDk1FpmtsBl0f52WCFBaFVdWp8+fBDGdLPD0EkC0V4xPL3PsiNUIL7O7j91fl/IO4Pz6Xmu2zdoDXSAV9tDaaozaGer+4T0G8Bc4l5JNBGMHIG2121kuv0HNkOd9BaNMzGBLrOGMBH+bbfIF1fCxwvv2F2NaOD2fcRRQu4DxxrqlwKBgQDROsLA8KwGmaq22a3s0zZbfLrBS6i+TV6MdST5TYuglzqC27v/yC2IIXFom3ycYS+MEaTwRTKZco8XALnl8b63rtekpYEybRiNy5axJJKd0cGip+RbkSjuqe3POkntWFMzU30Qlvz1N9aYPB7uUU5i2/F72H9Mx/G9ihsvMFD0xQKBgQDOp4Bk1pJ24ei+k+Skn0bIojjCQ2Ua9PYL1yS4qMA6EzMQST5ikZgAZWVmBJUXzbfjJW1BHrSxAcW+ypk4DkspVhaaWPG/Svi0abLgxWc7c9spdvBSUhSE2NrD4VYkeqEwmy6B9xOpBQk+aOZW/0+mcW47cQYJVZdgE+PEAaIrTQKBgQCE7LP2J/DicJYIfNsGbllGXkO3sf2OiVDcI0BOMnnWmL1PjZIuulpS9gw6zS2pnAS9FCiZjRzMZ/+IOang8GieAbJ2o78k7jJ/QyyFdhq/sRc34zotAlfi6Ipw8TMuWsLhBNWbyJEEqWjoZqmv9m+6VslgSPb3LL/kDu2eWS/VkQKBgQCAyOrvrDp2eBRpJ3mV/MMGCgtx4M8EPAVV7pa4EZ7Ci/YFrJiykZRiVP46liR66swCkoU3OM1flpxM3z4FDisOhyN0OZDIOltRGyt3YDowKMKGv765NjfD8FYmONUnMIw4hzjOPWnyzy3edH3rt/RaWjVyMQH+TLVrREDUaXDp0A==
  public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAuwXj/7le95G9v9MQmrRkHR1PaPG6Q0txkTVZFlPYeE+6Byeq0MG0xyHtPlfyt/sYyFRsz9eQxf602/3q2ZxUnmuE2xZLYGIfHTmtCfcXkKUjqo8T1J6BmlngXy3uUP3CGdUxw17TEToUWXqUtdZBJvcVBCuSAWduG4jBl/Fp2gS+6SIGhdnrArglSkyD/hNC7tHhymUnCm8ogH21XOCEI+eVSiswPkL24KDPsJfQu1EbfoRfStzYzsqftsQHc6noZfjJcZqKlZp0mVCZ7H2rYfM87G6F2NZwuRPtdNUruI+5iZmNkkDJZaG1EzW5dnbbkJFEQScWXJ2+9QXMfn5yMwIDAQAB
  expiration: 3600000
platform:
  internal=token: JZCpJYOspDqdk2Kj5DHxiQTeIR6_hHp12YljIob-CGY

