server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/usermanagementdb
spring.datasource.username=root
spring.datasource.password=2439

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

eureka.instance.prefer-ip-address=true

platform.internal-token=JZCpJYOspDqdk2Kj5DHxiQTeIR6_hHp12YljIob-CGY
