server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/usermanagementdb
spring.datasource.username=root
spring.datasource.password=2439

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

eureka.instance.prefer-ip-address=true

jwt.public-key=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAuwXj/7le95G9v9MQmrRkHR1PaPG6Q0txkTVZFlPYeE+6Byeq0MG0xyHtPlfyt/sYyFRsz9eQxf602/3q2ZxUnmuE2xZLYGIfHTmtCfcXkKUjqo8T1J6BmlngXy3uUP3CGdUxw17TEToUWXqUtdZBJvcVBCuSAWduG4jBl/Fp2gS+6SIGhdnrArglSkyD/hNC7tHhymUnCm8ogH21XOCEI+eVSiswPkL24KDPsJfQu1EbfoRfStzYzsqftsQHc6noZfjJcZqKlZp0mVCZ7H2rYfM87G6F2NZwuRPtdNUruI+5iZmNkkDJZaG1EzW5dnbbkJFEQScWXJ2+9QXMfn5yMwIDAQAB
platform.internal-token=JZCpJYOspDqdk2Kj5DHxiQTeIR6_hHp12YljIob-CGY
